### ISSUE TITLE
GGWP author, such a cool library that that doesn't working!

### ISSUE THREAD

**Issue by MairwunNx** [carmack78/OpenGLDotNet#2]
Just simple code

![image](https://user-images.githubusercontent.com/39625750/55673187-0b14a680-58ad-11e9-93c6-95df21e92771.png)

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write
 protected memory. This is often an indication that other memory is corrupt.
   at OpenGLDotNet.GLUT.glutInit(Int32* argcp, Byte** argv)
   at OpenGLDotNet.GLUT.Init(Int32[] argcp, String[] argv)
   at GL0x01.Program.Main() in C:\OpenGL\Projects\...\...\Program.cs:line 10
```

But it fix by removing null and create array with some string, but your example show community calling with null param. This is a very good example.

Well, here we are lucky, why lucky? Yes, because the library was able to load! If you use a pre-built debility library from the releases folder there will be an exception that the library cannot load! 

What did people do Nuget for? What did people do Releases tab in github? When it is possible to throw everything into the Releases folder in the project and throw it into the repository.

**You beat records in quality and attitude to those people who use your library!**

Let me know where you got these libraries from:
```
DevIL.dll
freeglut.dll
glut32.dll
glut32.old.dll
ILU.dll
ILUT.dll
```
I have not seen these libraries in Nuget dependencies. I have not seen these libraries in project resources. And again you broke the record in relation to the community! You just threw them into the debug folder!

What is the glu32.old library? Why keep old libraries if it is not clear where they are used?
What kind of library freeglut.dll? And why use it if there is glu32? glu32 not working or what?

After compiling the demo in the Releases folder does not work, it just crashes! I can't believe how you did it at all!

If the library is positioned as comfortably, why not make the simple overloaded GLUT.Init method without arguments? That will call GLUT.Init (new [] {0}, null).

How could this even be mentioned on the official opengl website as super comfortable opengl binding? If it just does not work.

I certainly understand that I can be blunt, but not so much that I could not call a simple method and get an exception!

I hope for the understanding of the author and the fact that he will fix his shoals with this library.

At a least, it will be placed on nuget, in github releases, the ready lib will be put, and all other libraries will be indicated in the file **third-party** or indicate where they will be taken from.

## Given that the library is mentioned in the official documentation, it would be nice to make it humanely

**Comment by sunkin351** [comment]
@MairwunNx This library, as it stands, has some really bad marshalling problems, and is not compatible with the 64-bit architecture. As such, I forked it and have been working on updating its internals, its API, and its and code organization for some time now. My modifications are free for all to see (and use ^^). As of writing this, my fork not currently in a usable or compilable state. I expect to have it completed by maybe January 2020 at the latest? Depends on if I can get help on updating it.

**Comment by withthelove** [comment]
@sunkin351  I know it’s been a long time, but can you elaborate on the Marshalling problems you found?

I found and fixed one in a helper function used by glShaderSource.   When I get a chance I was going to put in a pull request with the fix.   If there are other marshalling problems you can point me at, I can see about rolling fixes for them also.

**Comment by sunkin351** [comment]
@withthelove It's been so long, I don't remember what I found here. I remember the issue being a systemic misunderstanding of how marshalling should be done, though.

I found another project that met my needs at the time (Silk.NET), and now I'm working on something else entirely that doesn't use graphics directly.

I could have a gander now and tell you what pops out at me, if you're interested in that.

**Comment by withthelove** [comment]
Nah, it’s all good.  You’ve given me enough to at least know where to look.   I’ll scan through all the Marshal calls looking for trouble.  😃

Thanks for replying though!   Very kind of you to respond to a necropost about a project you’re not even using anymore. 😃
